#base image we need to specifiy version to aviod bugs
FROM node:16-alpine

#set up a working directory,
WORKDIR './app'

#copy package dot JSON to the current working directory  means [.] rep 
COPY package.json .

RUN npm install

#will copy everything else to current working directory 

COPY . .

#we can run our command to start up our project

CMD ["npm", "run", "start"]